name: vivebien
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: "3.5.0"

dependencies:
  analyzer: ^5.13.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
